<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/ModifiedCarSvcSchema.xsd"/>
      <rootElement name="WScars" namespace="http://org.packt.car.ws.schema"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/XML_Mapping.xsd"/>
      <rootElement name="processResponseForEach" namespace="http://xmlns.oracle.com/Validate_And_Transform/XSLT_Mapping/XML_Mapping"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU MAR 28 23:48:59 CET 2013]. -->
?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://org.packt.car.ws.schema"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns1="http://xmlns.oracle.com/Validate_And_Transform/XSLT_Mapping/XML_Mapping"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ud="http://www.oracle.com/XSL/Transform/java/org.packt.user.defined.ValueWithUnit"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 xsd ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ud ldap">
  <xsl:param name="test" select="oraext:generate-guid()"/>
  <xsl:variable name="varRabate">0.83</xsl:variable>
  <xsl:template match="/">
    <ns1:processResponseForEach>
      <xsl:for-each select="/ns0:WScars/ns0:listCars">
        <ns1:availableCars>          
          <ns1:carBrand>
            <xsl:value-of select="ns0:carType"/>
          </ns1:carBrand>
          <ns1:year>
            <xsl:value-of select="ns0:buildYear"/>
          </ns1:year>
          <ns1:milleage>
            <xsl:value-of select="ns0:milleage"/>
          </ns1:milleage>
          <ns1:price>
            <xsl:value-of select="round(ns0:pricePerDay * $varRabate)"/>
          </ns1:price>
          <xsl:choose>
            <xsl:when test='ns0:refNo != ""'>
              <ns1:ref>
                <xsl:value-of select="ns0:refNo"/>
              </ns1:ref>
            </xsl:when>
            <xsl:otherwise>
              <ns1:ref>
                <xsl:value-of select="$test"/>
              </ns1:ref>
            </xsl:otherwise>
          </xsl:choose>
        </ns1:availableCars>
      </xsl:for-each>
    </ns1:processResponseForEach>
  </xsl:template>
</xsl:stylesheet>
