package org.packt.bpel.sync;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://medion:7001/soa-infra/services/default/bpel-101-HelloWorld/helloworldprocess_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
  name="helloworldprocess_client_ep")
public class Helloworldprocess_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("org.packt.bpel.sync.Helloworldprocess_client_ep");
      URL baseUrl = Helloworldprocess_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Helloworldprocess_client_ep.class.getResource("http://medion:7001/soa-infra/services/default/bpel-101-HelloWorld/helloworldprocess_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://medion:7001/soa-infra/services/default/bpel-101-HelloWorld/helloworldprocess_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://medion:7001/soa-infra/services/default/bpel-101-HelloWorld/helloworldprocess_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://medion:7001/soa-infra/services/default/bpel-101-HelloWorld/helloworldprocess_client_ep?WSDL",
          e);
    }
  }

  public Helloworldprocess_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
                    "helloworldprocess_client_ep"));
  }

  public Helloworldprocess_client_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="HelloWorldProcess_pt")
  public org.packt.bpel.sync.HelloWorldProcess getHelloWorldProcess_pt()
  {
    return (org.packt.bpel.sync.HelloWorldProcess) super.getPort(new QName("http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
                                                                           "HelloWorldProcess_pt"),
                                                                 org.packt.bpel.sync.HelloWorldProcess.class);
  }

  @WebEndpoint(name="HelloWorldProcess_pt")
  public org.packt.bpel.sync.HelloWorldProcess getHelloWorldProcess_pt(WebServiceFeature... features)
  {
    return (org.packt.bpel.sync.HelloWorldProcess) super.getPort(new QName("http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
                                                                           "HelloWorldProcess_pt"),
                                                                 org.packt.bpel.sync.HelloWorldProcess.class,
                                                                 features);
  }
}
