package org.packt.bpel.sync;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebService(wsdlLocation="http://medion:7001/soa-infra/services/default/bpel-101-HelloWorld/helloworldprocess_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
  name="HelloWorldProcess")
@XmlSeeAlso(
  { org.packt.bpel.sync.gen.ObjectFactory.class })
public interface HelloWorldProcess
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess/HelloWorldProcess/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
    className="org.packt.bpel.sync.gen.ProcessResponse")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
    className="org.packt.bpel.sync.gen.Process")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
    name="result")
  public String process(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
      name="input")
    String input);
}
