
package org.packt.ws.jaxws.async;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DoReservationAsync", targetNamespace = "http://org.packt.ws.jaxws.async/reservation")
@SOAPBinding(style = javax.jws.soap.SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DoReservationAsync {


    /**
     * 
     * @param payload
     * @return
     *     returns javax.xml.ws.Response<org.packt.ws.jaxws.async.ReservationConfirmationType>
     */
    @WebMethod(operationName = "reserve")
    public Response<ReservationConfirmationType> reserveAsync(
        @WebParam(name = "ReservationEl", targetNamespace = "http://org.packt.ws.jaxws.async/elts", partName = "payload")
        ReservationType payload);

    /**
     * 
     * @param asyncHandler
     * @param payload
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "reserve")
    public Future<?> reserveAsync(
        @WebParam(name = "ReservationEl", targetNamespace = "http://org.packt.ws.jaxws.async/elts", partName = "payload")
        ReservationType payload,
        @WebParam(name = "reserveResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ReservationConfirmationType> asyncHandler);

    /**
     * 
     * @param payload
     * @return
     *     returns org.packt.ws.jaxws.async.ReservationConfirmationType
     */
    @WebMethod
    @WebResult(name = "ReservationConfirmationEl", targetNamespace = "http://org.packt.ws.jaxws.async/elts", partName = "payload")
    public ReservationConfirmationType reserve(
        @WebParam(name = "ReservationEl", targetNamespace = "http://org.packt.ws.jaxws.async/elts", partName = "payload")
        ReservationType payload);

}
