<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.packt.org/book/car"
     xmlns:ns="http://www.packt.org/book/car"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="BookCarSrvc">
        <plnk:role name="BookCarServicePortType">
            <plnk:portType name="ns:BookCarServicePortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.packt.org/book/car" location="BookCarService.wsdl"/>
</wsdl:definitions>
