<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CustomLog"
     targetNamespace="http://xmlns.oracle.com/ListsAndLogs/CustomLogging/CustomLog"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:client="http://xmlns.oracle.com/ListsAndLogs/CustomLogging/CustomLog"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CustomLog">
        <plnk:role name="CustomLogProvider" portType="client:CustomLog"/>
    </plnk:partnerLinkType>    
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/ListsAndLogs/CustomLogging/CustomLog" schemaLocation="xsd/CustomLog.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CustomLogRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="CustomLogResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="CustomLog">
        <wsdl:operation name="process">
            <wsdl:input message="client:CustomLogRequestMessage"/>
            <wsdl:output message="client:CustomLogResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
