package org.packt.bpel.sync;

import javax.xml.ws.WebFault;

@WebFault(faultBean="org.packt.bpel.sync.gen.Fault", targetNamespace="http://xmlns.oracle.com/bpel_101_HelloWorld_jws/bpel_101_HelloWorld/HelloWorldProcess",
  name="fault")
public class ProcessFaultMessage
  extends Exception
{
  private org.packt.bpel.sync.gen.Fault faultInfo;

  public ProcessFaultMessage(String message,
                             org.packt.bpel.sync.gen.Fault faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public ProcessFaultMessage(String message,
                             org.packt.bpel.sync.gen.Fault faultInfo,
                             Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public org.packt.bpel.sync.gen.Fault getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(org.packt.bpel.sync.gen.Fault faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)
